# -*- coding: utf-8 -*-
"""
Base Strategy Module

Abstract base class for all trading strategies.
All strategies must inherit from BaseStrategy and implement generate_signals().

# =============================================================================
# !!! КРИТИЧЕСКИЙ МОДУЛЬ - ИЗМЕНЯТЬ С ОСТОРОЖНОСТЬЮ !!!
# =============================================================================
# Этот модуль является БАЗОЙ для ВСЕХ стратегий, включая LIVE торговлю.
# Изменения в Signal, DailyCandle, StrategyData, StrategyConfig или
# BaseStrategy могут сломать ВСЕ стратегии одновременно!
#
# Если нужно добавить новые поля - добавляй с default значениями,
# чтобы не ломать существующий код.
#
# Последняя проверка: 2025-03-06
# =============================================================================
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Dict, Any, Optional


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    date: datetime
    symbol: str
    direction: str  # "LONG" or "SHORT"
    entry: float
    stop_loss: float
    take_profit: float
    reason: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    # Chain/Dedup fields (filled by chain_processor)
    signal_id: str = ""           # 20240115_BTCUSDT_LONG
    chain_id: str = ""            # BTCUSDT_LONG_C001
    chain_seq: int = 0            # Sequence within chain (1, 2, 3...)
    chain_total: int = 0          # Total signals in this chain
    chain_gap_days: int = 0       # Days since previous signal
    is_chain_first: bool = False  # First signal in chain
    is_chain_last: bool = False   # Last signal in chain


@dataclass
class DailyCandle:
    """Daily OHLCV candle with all Binance kline data."""
    date: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    quote_volume: float = 0.0           # USDT volume for liquidity checks
    trades_count: int = 0               # Number of trades
    taker_buy_volume: float = 0.0       # Taker buy volume (base asset)
    taker_buy_quote_volume: float = 0.0 # Taker buy volume (USDT)


@dataclass
class StrategyData:
    """
    All data needed for strategy signal generation.
    Passed to strategy's generate_signals() method.
    """
    symbol: str
    candles: List[DailyCandle]
    oi_history: List[Dict]      # Daily Open Interest
    ls_history: List[Dict]      # Daily Long/Short Ratio
    funding_history: List[Dict] # 8h Funding Rate


@dataclass
class StrategyConfig:
    """
    Strategy configuration parameters.
    Each strategy can define its own required parameters.
    """
    sl_pct: float = 5.0         # Stop Loss %
    tp_pct: float = 10.0        # Take Profit %
    max_hold_days: int = 14     # Max hold period
    lookback: int = 7           # Lookback period for calculations

    # Volume filter parameters (Доработка #2)
    order_size_usd: float = 100.0     # Order size in USDT
    min_volume_ratio: float = 0.001   # Max % of daily volume (0.1% = order < 0.1% of volume)

    # Strategy-specific parameters (optional)
    params: Dict[str, Any] = field(default_factory=dict)

    def get(self, key: str, default: Any = None) -> Any:
        """Get a parameter from params dict."""
        return self.params.get(key, default)


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    To create a new strategy:
    1. Inherit from BaseStrategy
    2. Set `name` and `description` class attributes
    3. Implement `generate_signals()` method
    4. Optionally override `default_config()` for strategy-specific defaults
    """

    name: str = "base"
    description: str = "Base strategy (abstract)"

    def __init__(self, config: Optional[StrategyConfig] = None):
        """Initialize strategy with configuration."""
        self.config = config or self.default_config()

    @classmethod
    def default_config(cls) -> StrategyConfig:
        """
        Return default configuration for this strategy.
        Override in subclasses for strategy-specific defaults.
        """
        return StrategyConfig()

    @abstractmethod
    def generate_signals(self, data: StrategyData) -> List[Signal]:
        """
        Generate trading signals from data.

        Args:
            data: StrategyData containing candles, OI, L/S, funding history

        Returns:
            List of Signal objects
        """
        pass

    # =========================================================================
    # !!! КРИТИЧЕСКИЕ ВСПОМОГАТЕЛЬНЫЕ МЕТОДЫ - НЕ ИЗМЕНЯТЬ !!!
    # =========================================================================
    # Эти методы используются ВСЕМИ стратегиями для получения данных.
    # Изменение логики здесь СЛОМАЕТ ВСЕ стратегии!
    # Последняя проверка: 2025-03-06
    # =========================================================================
    def _get_ls_for_date(self, ls_history: List[Dict], target_date: datetime) -> Optional[Dict]:
        """Get L/S ratio data for a specific date.

        !!! НЕ ИЗМЕНЯТЬ - ИСПОЛЬЗУЕТСЯ ВСЕМИ СТРАТЕГИЯМИ !!!
        """
        target_ts = int(target_date.timestamp() * 1000)

        best = None
        best_diff = float('inf')

        for ls in ls_history:
            ts = ls.get("timestamp", 0)
            diff = abs(ts - target_ts)
            if diff < best_diff and ts <= target_ts:
                best_diff = diff
                best = ls

        return best

    def _get_oi_for_date(self, oi_history: List[Dict], target_date: datetime) -> Optional[Dict]:
        """Get OI data for a specific date."""
        target_ts = int(target_date.timestamp() * 1000)

        best = None
        best_diff = float('inf')

        for oi in oi_history:
            ts = oi.get("timestamp", 0)
            diff = abs(ts - target_ts)
            if diff < best_diff and ts <= target_ts:
                best_diff = diff
                best = oi

        return best

    def _calculate_atr(self, candles: List[DailyCandle], period: int = 14) -> float:
        """Calculate Average True Range."""
        if len(candles) < period + 1:
            return 0.0

        tr_list = []
        for i in range(1, len(candles)):
            high = candles[i].high
            low = candles[i].low
            prev_close = candles[i-1].close

            tr = max(
                high - low,
                abs(high - prev_close),
                abs(low - prev_close)
            )
            tr_list.append(tr)

        if len(tr_list) < period:
            return sum(tr_list) / len(tr_list) if tr_list else 0.0

        return sum(tr_list[-period:]) / period

    def _calculate_adx(self, candles: List[DailyCandle], period: int = 14) -> float:
        """
        Calculate Average Directional Index (ADX).

        ADX measures trend strength (0-100):
        - 0-20: Weak/No trend
        - 20-40: Moderate trend
        - 40-60: Strong trend
        - 60-100: Very strong trend

        Args:
            candles: List of daily candles (need at least period*2 candles)
            period: ADX period (default 14)

        Returns:
            ADX value (0-100)
        """
        if len(candles) < period * 2:
            return 0.0

        # Calculate True Range, +DM, -DM
        tr_list = []
        plus_dm_list = []
        minus_dm_list = []

        for i in range(1, len(candles)):
            high = candles[i].high
            low = candles[i].low
            prev_high = candles[i-1].high
            prev_low = candles[i-1].low
            prev_close = candles[i-1].close

            # True Range
            tr = max(
                high - low,
                abs(high - prev_close),
                abs(low - prev_close)
            )
            tr_list.append(tr)

            # Directional Movement
            up_move = high - prev_high
            down_move = prev_low - low

            plus_dm = up_move if (up_move > down_move and up_move > 0) else 0
            minus_dm = down_move if (down_move > up_move and down_move > 0) else 0

            plus_dm_list.append(plus_dm)
            minus_dm_list.append(minus_dm)

        if len(tr_list) < period:
            return 0.0

        # Smoothed TR, +DM, -DM (Wilder's smoothing)
        def wilder_smooth(data: List[float], period: int) -> List[float]:
            smoothed = [sum(data[:period])]
            for i in range(period, len(data)):
                smoothed.append(smoothed[-1] - (smoothed[-1] / period) + data[i])
            return smoothed

        atr_smooth = wilder_smooth(tr_list, period)
        plus_dm_smooth = wilder_smooth(plus_dm_list, period)
        minus_dm_smooth = wilder_smooth(minus_dm_list, period)

        if len(atr_smooth) == 0:
            return 0.0

        # Calculate +DI, -DI, DX
        dx_list = []
        for i in range(len(atr_smooth)):
            if atr_smooth[i] == 0:
                continue

            plus_di = (plus_dm_smooth[i] / atr_smooth[i]) * 100
            minus_di = (minus_dm_smooth[i] / atr_smooth[i]) * 100

            di_sum = plus_di + minus_di
            if di_sum == 0:
                continue

            dx = abs(plus_di - minus_di) / di_sum * 100
            dx_list.append(dx)

        if len(dx_list) < period:
            return sum(dx_list) / len(dx_list) if dx_list else 0.0

        # ADX = smoothed DX
        adx_smooth = wilder_smooth(dx_list, period)

        return adx_smooth[-1] if adx_smooth else 0.0

    def _has_sufficient_volume(
        self,
        candle: DailyCandle,
        order_size: Optional[float] = None
    ) -> bool:
        """
        Check if there's sufficient volume for the order.

        Args:
            candle: Daily candle for the entry day (with quote_volume)
            order_size: Order size in USD (or use config.order_size_usd)

        Returns:
            True if volume is sufficient, False if should skip signal
        """
        size = order_size or self.config.order_size_usd
        min_ratio = self.config.min_volume_ratio

        # If no volume data, allow signal (don't block)
        if not hasattr(candle, 'quote_volume') or candle.quote_volume <= 0:
            return True

        # Check: order_size must be <= quote_volume * min_ratio
        # i.e., order must be less than 0.1% of daily volume
        max_order = candle.quote_volume * min_ratio
        return size <= max_order

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self.name}')"
