# -*- coding: utf-8 -*-
"""
ML module for signal enhancement.

This module provides ML-based filtering and optimization
for trading signals generated by backtester.
"""

from .adapter import BacktestDataAdapter
from .trainer_all import AllStrategiesTrainer
from .trainer_per_strategy import PerStrategyTrainer
from .filter import MLSignalFilter

__all__ = [
    'BacktestDataAdapter',
    'AllStrategiesTrainer',
    'PerStrategyTrainer',
    'MLSignalFilter',
]
